### ISSUE TITLE
BPMNs

### ISSUE THREAD

**Issue by mariejuenke** [FabianHen/AstroSphere#2]
https://demo.bpmn.io

- [x] Verkauf - Snack / Merch
- [x] Verkauf - Ticket
- [x] Nachbestellung - Snack Ticket
- [x] ?? Entwicklung -Merch
- [x] Veranstaltung vorbereiten
- [x] (intern) Buchung - Teleskope
- [x] Frschung - Informatonen anpassen

**Comment by mariejuenke** [comment]
[Verkauf_Merch_Snack.zip](https://github.com/FabianHen/AstroSphere/files/15390091/Verkauf_Merch_Snack.zip)
[Verkauf_Tickets.zip](https://github.com/FabianHen/AstroSphere/files/15390100/Verkauf_Tickets.zip)

**Comment by mariejuenke** [comment]
test

**Comment by olHannes** [comment]
Verbindungsänderung von "Bestellung abbrechen" zu Nachbestellung anlegen.
[Verkauf_Merch_Snack.zip](https://github.com/FabianHen/AstroSphere/files/15400442/Verkauf_Merch_Snack.zip)

**Comment by mariejuenke** [comment]
[Buchung_Teleskopez.zip](https://github.com/FabianHen/AstroSphere/files/15407889/Buchung_Teleskopez.zip)

**Comment by mariejuenke** [comment]
done /close
